apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: deploy-test
  name: deploy-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: deploy-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: deploy-test
    spec:
      containers:
      - image: sharor/helloworld
        imagePullPolicy: IfNotPresent
        name: deploy-test
      restartPolicy: Always
